collateral provision implementation
ElrondNetwork/sc-stablecoin-rs pull request #16
Opened 2022-07-12 22:46 UTC by psorinionut

2022-07-18 16:31 UTC, claudiu725 requested changes

2022-07-18 16:31 UTC, claudiu725 commented on stablecoin-v3/src/lib.rs
> +        let base_collateral_token_id = self.base_collateral_token_id().get();
A check on `cp_token_id` is missing. Currently the caller can send any token and it will be accepted.

2022-07-18 16:31 UTC, claudiu725 commented on stablecoin-v3/src/lib.rs
> +            }
Optional suggestion - move the zero-check inside the `update_rewards` method as it's duplicated in 2 places.

2022-07-18 16:31 UTC, claudiu725 commented on stablecoin-v3/src/lib.rs
> +            };
Duplicated logic.
Suggestion - move the logic to a new method `compute_rewards` and call it twice with something like:
```
let stablecoin_rewards = self.compute_rewards(
    self.stablecoin().get_token_id(),
    &cp_token_attributes.stablecoin_reward_per_share
);
let collateral_rewards = self.compute_rewards(
    self.base_collateral_token_id().get(),
    &cp_token_attributes.collateral_reward_per_share
);
```

2022-07-19 12:42 UTC, psorinionut commented on stablecoin-v3/src/lib.rs
> +        let base_collateral_token_id = self.base_collateral_token_id().get();
Done.

2022-07-19 12:42 UTC, psorinionut commented on stablecoin-v3/src/lib.rs
> +            }
Done.

2022-07-19 12:42 UTC, psorinionut commented on stablecoin-v3/src/lib.rs
> +            };
Done.

2022-07-19 14:21 UTC, claudiu725 approved these changes

2022-07-21 16:41 UTC, merged